# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_register', '0002_user_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('receiving_poke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_poke', to='login_register.User')),
                ('sending_poke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_poke', to='login_register.User')),
            ],
            options={
                'db_table': 'pokes',
            },
        ),
    ]
